version: '3.4'

services:
  app:
    container_name: notes-app-go
    build:
      context: .
      dockerfile: Dockerfile
    command: ./postgres-ready.sh db ./.bin/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432